"""
data.py — The FRIENDS episode dataset.
"""

episodes = [
    {"season": 1, "episode": 1, "title": "The Pilot",
     "description": "Rachel arrives at Central Perk in a wedding dress after running away from her wedding. Monica lets Rachel move in and the whole group welcomes her. The friends support each other through the change.",
     "category": "Friendship"},
    {"season": 1, "episode": 2, "title": "The One with the Sonogram at the End",
     "description": "Ross finds out his ex-wife Carol is pregnant. He goes to the sonogram appointment and struggles with the news. Meanwhile Monica stresses about dinner and tries to impress her parents.",
     "category": "Family"},
    {"season": 1, "episode": 7, "title": "The One with the Blackout",
     "description": "A citywide blackout hits New York. Ross tries to tell Rachel how he feels about her but keeps getting interrupted. Chandler gets stuck in an ATM vestibule with a beautiful model. Romance fills the air.",
     "category": "Romance"},
    {"season": 1, "episode": 15, "title": "The One with the Stoned Guy",
     "description": "Monica gets the chance to cook for a restaurateur who could offer her a head chef position. She prepares an elaborate meal to impress him. Meanwhile Chandler gets a promotion and considers his options.",
     "category": "Career"},
    {"season": 1, "episode": 18, "title": "The One with All the Poker",
     "description": "Rachel goes on several interviews hoping to land a position in fashion. The guys teach the girls how to play poker. Rachel channels her frustration about rejection letters into the game.",
     "category": "Career"},
    {"season": 1, "episode": 24, "title": "The One Where Rachel Finds Out",
     "description": "Chandler accidentally reveals that Ross is in love with Rachel. Rachel realizes her feelings and rushes to the airport to tell Ross, but he arrives with his new girlfriend Julie.",
     "category": "Romance"},
    {"season": 2, "episode": 5, "title": "The One with Five Steaks and an Eggplant",
     "description": "The group is divided when three of them earn much less money than the other three. They argue about splitting expensive dinner bills and concert tickets. Eventually they work through it together.",
     "category": "Friendship"},
    {"season": 2, "episode": 7, "title": "The One Where Ross Finds Out",
     "description": "Rachel leaves a drunken voicemail confessing her feelings to Ross. Ross listens to the message and confronts Rachel. They share a passionate kiss at Central Perk, beginning their love story.",
     "category": "Romance"},
    {"season": 2, "episode": 14, "title": "The One with the Prom Video",
     "description": "The group watches an old prom video that reveals Ross was ready to take Rachel to prom when her date was late. Moved by his devotion, Rachel kisses Ross and they become a couple.",
     "category": "Romance"},
    {"season": 3, "episode": 2, "title": "The One Where No One's Ready",
     "description": "Ross needs everyone ready for a museum work banquet but nobody cooperates. Joey and Chandler fight over a chair, Monica obsesses over a phone message from a guy she is dating, and everyone tests each other's patience.",
     "category": "Friendship"},
    {"season": 3, "episode": 9, "title": "The One with the Football",
     "description": "The gang plays a Thanksgiving football match. Monica and Ross revive their childhood rivalry. The competitive spirit brings everyone together for a hilarious holiday contest in the park.",
     "category": "Friendship"},
    {"season": 3, "episode": 15, "title": "The One Where Ross and Rachel Take a Break",
     "description": "Ross and Rachel have a huge fight about their relationship. Rachel suggests they take a break and Ross sleeps with someone else. Their love story takes a devastating turn that haunts the whole series.",
     "category": "Romance"},
    {"season": 4, "episode": 3, "title": "The One with the Cuffs",
     "description": "Chandler gets handcuffed to a chair in his boss's office. Joey auditions for a big movie role and desperately wants the part. Monica starts as a chef at a terrible diner to keep her resume going.",
     "category": "Career"},
    {"season": 4, "episode": 12, "title": "The One with the Embryos",
     "description": "The group plays a trivia contest to see who knows each other best. Guys versus girls. Monica and Rachel lose their apartment to Joey and Chandler. Everyone learns surprising things about each other.",
     "category": "Friendship"},
    {"season": 5, "episode": 8, "title": "The One with All the Thanksgivings",
     "description": "Everyone shares their worst Thanksgiving memories through flashbacks. Young Monica and young Chandler appear. Monica accidentally cuts off Chandler's toe. Childhood stories and holiday traditions take center stage.",
     "category": "Family"},
    {"season": 5, "episode": 14, "title": "The One Where Everybody Finds Out",
     "description": "Phoebe discovers Monica and Chandler are secretly dating. She and Rachel try to get them to confess by flirting with Chandler. Chandler finally declares his love for Monica in front of everyone.",
     "category": "Romance"},
    {"season": 6, "episode": 6, "title": "The One on the Last Night",
     "description": "Chandler moves in with Monica and Rachel has to find a new roommate. They spend a last night in the old apartment together. Joey and Chandler share an emotional farewell as roommates.",
     "category": "Friendship"},
    {"season": 6, "episode": 15, "title": "The One That Could Have Been",
     "description": "Everyone imagines alternate lives: Ross is still married to Carol, Rachel married Barry, Monica is still overweight, Joey is a soap star, Phoebe is a stockbroker, and Chandler pursues his dream of writing.",
     "category": "Career"},
    {"season": 6, "episode": 25, "title": "The One with the Proposal",
     "description": "Chandler plans to propose to Monica but Richard shows up and confesses he still loves her. Monica ultimately chooses Chandler and they get engaged in a room full of candles. A deeply romantic moment.",
     "category": "Romance"},
    {"season": 7, "episode": 17, "title": "The One with the Cheap Wedding Dress",
     "description": "Monica hunts for a bargain wedding dress. Chandler hates his job and decides to quit and pursue advertising. Ross starts dating his student Elizabeth despite the university rules about relationships.",
     "category": "Career"},
    {"season": 8, "episode": 1, "title": "The One After 'I Do'",
     "description": "At the wedding reception Rachel reveals she is pregnant. Everyone tries to figure out who the father is. Ross eventually learns he is going to be a dad again. The group rallies around the news.",
     "category": "Family"},
    {"season": 8, "episode": 24, "title": "The One Where Rachel Has a Baby",
     "description": "Rachel goes into labor and spends hours in the hospital. Ross stays by her side as she gives birth to Emma. The arrival of the newborn brings the whole family together in a deeply moving scene.",
     "category": "Family"},
    {"season": 9, "episode": 7, "title": "The One with Ross's Inappropriate Song",
     "description": "Ross discovers that singing makes baby Emma laugh. Monica and Chandler explore buying a house. Joey and Rachel navigate an awkward new dynamic in the apartment together.",
     "category": "Family"},
    {"season": 10, "episode": 12, "title": "The One with Phoebe's Wedding",
     "description": "Phoebe and Mike get married in a beautiful outdoor ceremony during a snowstorm. Monica takes over as planner and drives everyone crazy. Joey officiates and the whole group celebrates together.",
     "category": "Family"},
    {"season": 10, "episode": 17, "title": "The Last One",
     "description": "Rachel is about to leave for a job in Paris. Ross races to the airport to confess his love. Rachel gets off the plane and they reunite. The group leaves the apartment together one last time.",
     "category": "Romance"},
]
